### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by elalfer** [elalfer/IoT-Cronus#3]
Rename `iCalValveControl` to `iCalRelayControl`, and `IValveControl` to `IRelayControl`

**Comment by shr7** [comment]
I'd like to work on this. 
Any specific name you'd like me to rename it to?

**Comment by shivan1b** [comment]
Hello, I'd like to take this one. Please let me know if no one else is working on this.

**Comment by elalfer** [comment]
@shivan1b yup, feel free to take this one.
